service: layer
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1
  profile: serverless
  environment:
    variable1: value1

#package:
#  patterns:
#    - '!exclude-me.js'
#    - '!exclude-me-dir/**'
#    - include-me.js
#    - include-me-dir/**


layers:
  dayjs:
    path: ./
    name: ${sls:stage, 'test'}-dayjs